### PR TITLE
Docs/restructure the examples

### PR DESCRIPTION
**Pull request by programarivm**
This is a continuation of https://github.com/pymupdf/PyMuPDF-Utilities/pull/52

### CODE REVIEW

**Review by JorjMcKie — APPROVED** [review]

**Comment by JorjMcKie** [comment]
Thank you very much for this big effort, @programarivm!

Before I perform the merge let me ask you if you have signed the [Artifex Contributor License Agreement](https://artifex.com/contributor/) from Artifex?
Please drop me a short note if you have, and I will promptly execute the merge.

Please have a look there otherwise.

Thanks again!

**Comment by JorjMcKie** [comment]
Just confirming the signing process of the Contributor License agreement.
Your signature is required if you or your company haven't done it before:
Please download, print and sign the agreement.
Then send a scanned-in copy of it via e-mail to either henry.stiles@artifex.com or to myself, jorj.x.mckie@outlook.de.

Thank you very much in advance!

**Comment by programarivm** [comment]
Thank you @JorjMcKie, I just sent a copy of the Contributor License Agreement signed.

**Comment by JorjMcKie** [comment]
PR merged.
Thank you very much again for your contribution!

**Pull request merged**
