### PR TITLE
Issue/88 merge the demo scripts into the examples folder

### PR DESCRIPTION
**Pull request by programarivm**
Closes https://github.com/pymupdf/PyMuPDF-Utilities/issues/88

### CODE REVIEW

**Comment by programarivm** [comment]
@JorjMcKie this PR is ready to merge, thanks!

**Comment by JorjMcKie** [comment]
@programarivm - this affects a **lot** of the script - actually all of them. This makes it impractical or even impossible to do a review just based on looking at the PR itself:
Can you please give me an idea what the final folder layout of the repo would look like? Something like this maybe
```
exammples
    folder1: contains scripts like ...
    folder2: contains scripts like ...  
        folder21
... etc.
```
That would make it much easier for me to see what would happen by the merge.
Of yourse we would have to change all the references in the PyMuPDF in RTD again ...

Thank you!

**Comment by programarivm** [comment]
Before | After
-------| -----
[PIL2fitz.py](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/demo/PIL2fitz.py) | [examples/convert-image/convert.py](https://github.com/programarivm/PyMuPDF-Utilities/blob/issue/88-merge-the-demo-scripts-into-the-examples-folder/examples/convert-image/convert.py)

**Comment by JorjMcKie** [comment]
Ok, then how about following the structure of topics one level below the "Recipes" section of the documentation. We do already today refer to example script from there.
So it probably makes not much sense to establish a **_different_** folder structure inside the examples folder.

**Comment by JorjMcKie** [comment]
You probably should also talk to @jamie-lemon about this: he is working on improving the RTD documentation structure.

**Comment by JorjMcKie** [comment]
@programarivm / @jamie-lemon In the future we should probably turn round the requirement:
For any new script in this repository there needs to be a referral as to which Recipe section it belongs. If there is no suitable sub-section yet, we would need a larger round of decision makers to either extend the number of sub-sections, or even reject the example script.

**Comment by programarivm** [comment]
@JorjMcKie and @jamie-lemon, what about: (1) merge this PR, (2) hold off on refactoring the examples and (3) update the links?

**Comment by JorjMcKie** [comment]
Ok, gentlemen, thanks for all your feedbacks. I will go ahead and do the merge here.

**Pull request merged**
