### PR TITLE
Update multi_column.py

### PR DESCRIPTION
**Pull request by paluigi**
Added header removal option for `column_boxes` function and script

### CODE REVIEW

**Review by JorjMcKie — APPROVED** [review]
Thank you for your contribution!

**Comment by JorjMcKie** [comment]
Before I can merge your PR, you need to confirm that you have read and accept the Artifex Contributor License Agreement (CLA), available [here](https://artifex.com/contributor/).

It is sufficient if you add a post in this thread with some wording like "I have read and herewith accept the Artifex CLA".
This is required only once - you will be covered for your many future contributions 😉.

Thank you.

**Comment by paluigi** [comment]
I have read and herewith accept the Artifex CLA

**Comment by miriam-z** [comment]
Hi @JorjMcKie , how do we use multi_column since I only did pip install PyMuPDF:

```
import fitz
from multi_column import column_boxes
```

Says cannot resolve multi_column

**Comment by JorjMcKie** [comment]
Installation of PyMuPDF is good to start with. Then copy file https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/text-extraction/multi_column.py to your script's folder and you should be ok.

**Pull request merged**
